name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - jupyterlab
  - qgrid
  - pip
  - pip:
    - qgrid
    - pandas
    - ipywidgets
    - jupyter_contrib_nbextensions
