name: example-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - jupyterlab
  - qgrid
  - pip
  - pip:
    - pandas==1.0.0
    - ipywidgets
    - jupyter_contrib_nbextensions
